name: Baseline Production Database

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rollback:
    uses: orlandorode97/gh-example/.github/workflows/baseline_migration.yml@example
    permissions:
      id-token: write
      contents: read
    with:
      environment: production
      directory: prisma-gh
