name: Trigger Migrations to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      branch:
        description: The branch of the migration repo
        required: true
        type: string

jobs:
  call-deploy-migrations:
    uses: orlandorode97/gh-example/.github/workflows/deploy-migrations.yml@example
    with:
      environment: ${{ inputs.environment }}
      branch: ${{ inputs.branch }}
      directory: prisma-gh
