name: Trigger Migrations to production

on:
  push:
    branches:
      - master

jobs:
  call-deploy-migrations:
    uses: orlandorode97/gh-example/.github/workflows/deploy_migrations.yml@example
    permissions:
      id-token: write
      contents: read
    with:
      environment: production
      directory: prisma-gh
      branch: master
