name: Trigger Mark Applied Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3
      migration_name:
        type: string
        description: The migration to mark as applied

jobs:
  mark-applied-migration:
    uses: orlandorode97/gh-example/.github/workflows/mark_applied_migration.yml@example
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
      directory: prisma-gh
      migration_name: ${{ inputs.migration_name }}
