name: Trigger Rollback Failed Migration in Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3

jobs:
  call-deploy-migrations:
    uses: orlandorode97/gh-example/.github/workflows/rollback_staging_failed_migration.yml@example
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
      branch: ${{ github.ref_name }}
      directory: prisma-gh
