name: Trigger Rollback Migration in Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The namespace where migrations will be deployed
        required: true
        type: choice
        options:
          - stage1
          - stage2
          - stage3

jobs:
  rollback:
    uses: orlandorode97/gh-example/.github/workflows/rollback_migration.yml@example
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ inputs.environment }}
      directory: prisma-gh
      branch: ${{ github.ref }}
